<a href="https://colab.research.google.com/github/eunseochu/YB_2nd_Fri/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%99%84%EB%B2%BD_%EA%B0%80%EC%9D%B4%EB%93%9C_%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **3. 넘파이**

#### **1) 넘파이란?**

파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 하므로 빠른 연산 속도를 보장
- 파이썬 기반의 많은 과학과 공학 패키지는 넘파이에 의존

#### **2) 넘파이의 중요성**

데이터는 2차원 형태의 행과 열로 이루어져있으며, 이에 대한 다양한 가공과 변환, 여러가지 통계용 함수의 적용 등이 필요
- 대표적인 데이터 처리 패키지인 판다스의 편리성에는 미치지 못함
- 그러나 많은 머신러닝 알고리즘은 넘파이 기반으로 작성
- 알고리즘의 입력 데이터와 출력 데이터를 넘파이 배열 타입으로 사용하기 때문에 넘파이를 이해하는 것은 매우 중요

#### **3) 넘파이 ndarray 개요**

ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행 가능
- shape 변수: ndarray의 크기 (행과 열의 수)를 튜플 형태로 지녀 ndarray 배열의 차원을 알 수 있음





> **np.array() 사용법**<br/>
ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray 반환 <br/>
**ndarray.shape는 ndarray의 차원과 크기**를 튜플(tuple) 형태로 나타냄










In [2]:
import numpy as np
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) # 1차원 data

array2 = np.array([[1,2,3], 
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape) # 2개의 row, 3개의 column

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape) # 2차원 data

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


데이터값으로는 서로 동일하나 차원이 달라 오류가 발생하는 경우가 빈번하므로 주의




> **ndarray.ndim을 통해 각 array의 차원 확인 <br/>**
array() 함수의 인자로는 파이썬의 리스트 객체가 주로 사용됨 <br/>
리스트 [ ]는 1차원이고, 리스트의 리스트 [ [ ] ]는 2차원과 같은 형태로 배열의 차원과 크기를 쉽게 표현 가능



In [4]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim ))

array1: 1차원, array2: 2차원, array3:  2차원


#### **4) ndarray의 데이터 타입**
ndarray의 데이터 타입은 숫자 값, 문자열 값, 불 값 등 모두 가능 <br/>
- 숫자형: int형 (8bit, 16bit, 32bit), unsigned int형 (8bit, 16bit, 32bit), float형 (16bit, 32bit, 64bit, 128bit), complex형 (더 큰 숫자 값이나 정밀도)
- ndarray 내의 데이터 타입은 연산의 특성 상 같은 데이터 타입만 가능 (한 개의 ndarray 객체에 int와 float가 공존 불가능)

> **drtype 특성을 통해 ndarray 내의 데이터 타입 확인** <br/>
서로 다른 데이터 타입을 가질 수 있는 리스트와는 다르게 ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능


In [5]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


> **int형과 float형이 섞인 리스트 ndarray로 변경 <br/>**
만일 다른 데이터 유형이 섞인 리스트르 ndarry로 변경 시 데이터 크기가 더 큰 타입으로 형 변환 일괄 적용

In [6]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) # 문자열 값 (유니코드) 으로 일괄 변환

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # float형으로 일괄 변환

['1' '2' 'test'] <U21
[1. 2. 3.] float64


> **astype() 메서드로 ndarray 내 데이터 타입 변경** <br/>
astype()에 인자로 원하는 타입을 문자열로 지정 <br/>
데이터 타입 변경 시 대용량 데이터의 ndarray를 만들 때 많은 메모리가 사용되기에, 메모리 절약 시 주로 이용

In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype) # int32형 -> float64형

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype) # float64형 -> int32형 (소수점 이하 사라짐)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

#### **5) ndarray를 편리하게 생성하기 - arange, zeros, ones**
특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화에 쉽게 생성해야 할 필요가 있는 경우 존재 <br/>
주로 test용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용


> **arange()** <br/>
0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터 값으로 변환 <br/>
파이썬 표준 함수인 range()와 유사 (array를 range()로 표현) <br/>
- default 함수 인자: stop
- 0부터 stop 값인 10에서 -1을 더한 9까지의 연속 숫자 값으로 구성된 1차원 ndarray 생성

In [9]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


> **zeros(), ones()** <br/>
함수 인자로 dtype을 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채움
- zeros(): 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
- ones(): 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환


In [10]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### **6) ndarray의 차원과 크기를 변경하는 reshape()** <br/>
reshape() 메서드는 ndarray를 특정 차원 및 크기로 변환

> **reshape() 사용법 <br/>**
변환을 원하는 크기를 함수 인자로 부여

In [11]:
array1 = np.arange(10)
print('array1: \n', array1)

array2 = array1.reshape(2,5)
print('array2: \n', array2) # 2 row 5 column

array3 = array1.reshape(5,2)
print('array3: \n', array3) # 5 row 2 column

array1: 
 [0 1 2 3 4 5 6 7 8 9]
array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


> **reshape() 오류** <br/>
지정된 사이즈로 변경이 불가능하면 오류 발생

In [13]:
array1.reshape(4,3) # (10,) data를 (4,3) shape 형태로 변경 불가능

ValueError: ignored

> **reshape() 활용: 인자로 -1을 적용 (1) <br/>**
-1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환 <br/>

In [15]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape) # 고정된 5개 column에 맞는 row 자동 생성
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape) # 고정된 5개 row에 맞는 column 자동 생성

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4) # 고정된 4개의 row에 맞는 column 자동 생성 - 없어서 error

> **reshape() 활용: 인자로 -1을 적용 (2) <br/>**
reshape(-1,1) 형태로 주로 사용 <br/>
- 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 row를 가지되 반드시 1개의 column을 가진 ndarray로 변환됨을 보장 <br/>
- 여러 개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용

In [17]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist()) # tolist() 메서드를 통해 리스트 자료형으로 변환 가능

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5d:\n', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5d:
 (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


#### **7. 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱 (indexing)**
넘파이에서 ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 함 <br/>

 **1. 특정한 데이터만 추출**: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터 반환 <br/>

 **2. 슬라이싱 (Slicing):** <br/>

-  연속된 인덱스상의 ndarray 추출. 
- ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray 반환 <br/>


 **3. 팬시 인덱싱 (Fancy Indexing)**: 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray 반환 <br/>

 **4. 불린 인덱싱 (Boolean indexing):**
- 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반
- True에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환




> **단일 값 추출 (1)** <br/>
ndarray 객체에 해당하는 위치의 인덱스 값을 [ ] 안에 입력



In [19]:
# 1부터 9까지의 1차원 ndarray todtjd
array1 = np.arange(start = 1, stop = 10)
print('array1:', array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:', value)
print(type(value)) # ndarray type이 아닌 ndarray 내 데이터 값 의미

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


> **단일 값 추출 (2)** <br/>
인덱스에 마이너스 기호를 이용하면 맨 뒤에서부터 데이터 추출 가능 <br/>
- -1은 맨 뒤의 데이터 값
- -2는 맨 뒤에서 두 번째에 있는 데이터 값

In [20]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


> **단일 값 추출 (3): ndarray 내 데이터값 수정** <br/>
단일 인덱스를 이용해 ndarray 내 데이터값도 간단히 수정 가능

In [21]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]




> **단일 값 추출 (4): 다차원 ndarray에서 추출 <br/>**
다차원의 경우 콤마(,)로 분리된 row와 column 위치의 인덱스를 통해 접근 <br/>
ndarray에서는 row, column이 아닌 axis0, axis1으로 표현 
- ex. [row = 0, col = 1] = [axis0 = 0, axis1 = 1]
- 다차원 ndarray에서는 축(axis)에 따른 연산을 지원



In [22]:
# 1차원 andarray를 2차원의 3x3 ndarray로 변환후 [row, col]을 이용해 2차원 ndarray에서 데이터 추출
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3) # 3x3으로 변환
print(array1)

print('(row = 0, col = 0) index 가리키는 값:', array2d[0, 0])
print('(row = 0, col = 1) index 가리키는 값:', array2d[0, 1])
print('(row = 1, col = 0) index 가리키는 값:', array2d[1, 0])
print('(row = 2, col = 2) index 가리키는 값:', array2d[2, 2])

[9 2 3 4 5 6 7 8 0]
(row = 0, col = 0) index 가리키는 값: 1
(row = 0, col = 1) index 가리키는 값: 2
(row = 1, col = 0) index 가리키는 값: 4
(row = 2, col = 2) index 가리키는 값: 9




> **슬라이싱 (1)** <br/>
':' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출 가능 <br/>
- 단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입 <br/>
- ':' 사이에 시작 인덱스와 종료 인덱스를 표시하면 **시작 인덱스에서 종료 인덱스-1 위치**에 있는 데이터의 ndarray를 반환 <br/>


In [23]:
array1 = np.arange(start = 1, stop = 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


> **슬라이싱 (2)** <br/>
슬라이싱 기호인 ':' 사이의 시작, 종료 인덱스는 생략 가능 <br/>
- ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주 <br/>
- ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주 <br/>
- ':' 기호 앞/뒤에 시작/종료 인덱스를 모두 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [24]:
array1 = np.arange(start = 1, stop = 10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [25]:
# 2차원 ndarray 슬라이싱
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


> **슬라이싱 (3)** <br/>
2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray 반환 <br/>
- 2차원에서 뒤에 오는 인덱스를 없애면 axis 0(row)의 첫번째 row ndarry 반환 <br/>
- 3차원에서 뒤에 오는 인덱스를 없애면 2차원 ndarray 반환

In [26]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


#### **8. 팬시 인덱싱**
팬시 인덱싱 (Facny Indexing)은 리스트나 ndarry로 인덱스 집합을 지정하면 **해당 위치의 인덱스에 해당하는 ndarray를 반환**하는 인덱싱 방식

In [28]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2] # row 축에 팬시 인덱싱, column축에 단일 값 인덱싱 2: (row, col) = (0, 2), (1, 2)
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2] # ((0, 0), (0, 1)), ((1, 0), (1, 1))
print('array2d[[0, 1], 0:1] =>', array4.tolist())

array5 = array2d[[0, 1]] # ((0, :), (1, :))
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:1] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


#### **9. 불린 인덱싱**
불린 인덱싱 (Boolean indexing)은 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용 <br/>
- for loop/if else문보다 훨씬 간단하게 구현 <br/>
- ndarray의 인덱스를 지정하는 [ ] 내에 조건문 그대로 기재

In [29]:
array1d = np.arange(start = 1, stop = 10)
# [ ] 안에 array1 > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]




> **불린 인덱싱 조건 필터링 과정** <br/>
ndarray 객체에 조건식을 붙이면 False, True로 이루어진 ndarray 객체 반환 후, <br/>
False 값은 무시하고 True 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 변환
- Step 1: array1d > 5와 같이 ndarray 필터링 조건을 [ ] 안에 기재
- Step 2: False 값은 무시하고 True 값에 해당하는 인덱스 값만 저장 (True값 자체인 1이 아닌 True값을 가진 인덱스를 저장)
- Step 3: 저장된 인덱스 데이터 세트로 ndarray 조회





In [31]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [30]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 : ', array3)

불린 인덱스로 필터링 결과 :  [6 7 8 9]


In [32]:
# 위와 동일 
indexes = np.array([5, 6, 7 ,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


#### **10. 행렬의 정렬 - sort()**
행렬을 정렬하는 대표적인 방법인 np.sort()와 ndarray.sort()



> **행렬 정렬 (1) <br/>**
np.sort()와 같이 넘파이에서 sort()를 호출하는 방식과 ndarray.sort()와 같이 행렬 자체에서 sort()를 호출하는 방식
- np.sort(): **원 행렬은 그대로 유지**한 채 원 행렬의 정렬된 행렬을 반환
- ndarray.sort(): **원 행렬 자체를 정렬한 형태로 변환**하며 반환 값은 None


In [34]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1) # 원본 행렬 변경하지 않고 정렬된 형태로 반환
print('np.sort() 호출 후 원본 행렬:', org_array) 

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2) # 원본 행렬 자체를 정렬한 값으로 변환
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


> **행렬 정렬 (2) <br/>**
np.sort()나 ndarray.sort() 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬 <br/>
내림차순으로 정렬하기 위해서는 [::-1]를 적용

In [36]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


> **행렬 정렬 (3) <br/>**
행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 row / column 방향으로 정렬 수행 가능

In [37]:
array2d = np.array([[8, 12],
                    [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('row 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('column 방향으로 정렬:\n', sort_array2d_axis1)

row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### **11. 정렬된 행렬의 인덱스를 반환하기 - argsort()**

원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할때 np.argsort() 사용
- 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환



> **원본 행렬 정렬 시의 인덱스 값 구하기 (1)**



In [38]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


> **원본 행렬 정렬 시의 인덱스 값 구하기 (2)** <br/>
내림차순으로 정렬 시 [::-1] 적용

In [39]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


> **argsort()의 활용** <br/>
argsort()는 넘파이에서 활용도가 매우 높음 <br/>
- 넘파이의 ndarray는 메타 데이터 (ex. RDBMS의 TABLE column, 판다스 DataFrame colum)를 가질 수 없음 <br/>
- 따라서, 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야만 함 <br/>
- np.argsort()를 통해 반환된 인덱스를 팬시 인덱스를 적용해 추출하는 방식 사용

In [40]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


#### **12. 선형대수 연산 - 행렬 내적과 전치 행렬 구하기**
넘파이에서는 다양한 선형대수 연산을 지원하며, 그 중에서도 행렬 내적과 전치 행렬은 가장 많이 사용되는 기본 연산



> **행렬 내적(행렬 곱) <br/>**
행렬 내적은 행렬 곱이며, 두 행렬 A와 B의 내적은 np.dot()을 통해 계산 가능 <br/>
- 두 행렬 A와 B의 내적은 왼쪽 행렬의 row와 오른쪽 행렬의 column의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값
- 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 내적 연산 가능



In [41]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]




> **전치 행렬 <br/>**
원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬로 transpose()를 통해 계산 가능
- 2x2 행렬 A가 있을 경우 A 행렬의 1행 2열의 원소를 2행 1열의 원소로, 2행 1열의 원소를 1행 2열의 원소로 교환



In [42]:
A = np.array([[1, 2],
             [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
